"""empty message

Revision ID: 10265d89bd4
Revises: 8fe8a5f5de
Create Date: 2015-09-11 17:00:33.020402

"""

# revision identifiers, used by Alembic.
revision = '10265d89bd4'
down_revision = '8fe8a5f5de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('bun', sa.String(length=3), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'bun')
    ### end Alembic commands ###
