"""empty message

Revision ID: 113472c3507
Revises: 30214be263a
Create Date: 2015-09-11 17:50:00.363785

"""

# revision identifiers, used by Alembic.
revision = '113472c3507'
down_revision = '30214be263a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
