"""empty message

Revision ID: 14e32deb6bf
Revises: 58de734bd40
Create Date: 2015-08-15 22:54:25.373330

"""

# revision identifiers, used by Alembic.
revision = '14e32deb6bf'
down_revision = '58de734bd40'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'name')
    ### end Alembic commands ###
