"""empty message

Revision ID: 1c8e438ef34
Revises: 7d32716e43
Create Date: 2015-08-17 11:45:46.009643

"""

# revision identifiers, used by Alembic.
revision = '1c8e438ef34'
down_revision = '7d32716e43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    ### end Alembic commands ###
