"""empty message

Revision ID: 1e377573b03
Revises: 14e32deb6bf
Create Date: 2015-08-15 23:05:53.073400

"""

# revision identifiers, used by Alembic.
revision = '1e377573b03'
down_revision = '14e32deb6bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'material', ['matnr'])
    op.drop_column('material', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'material', type_='unique')
    ### end Alembic commands ###
