"""empty message

Revision ID: 2ab666b1e1d
Revises: 3c2e3309046
Create Date: 2015-09-11 17:47:20.325868

"""

# revision identifiers, used by Alembic.
revision = '2ab666b1e1d'
down_revision = '3c2e3309046'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
