"""empty message

Revision ID: 3a3f6f8e6c
Revises: 10265d89bd4
Create Date: 2015-09-11 17:41:33.194480

"""

# revision identifiers, used by Alembic.
revision = '3a3f6f8e6c'
down_revision = '10265d89bd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
