"""empty message

Revision ID: 3c2e3309046
Revises: 3a3f6f8e6c
Create Date: 2015-09-11 17:45:57.563433

"""

# revision identifiers, used by Alembic.
revision = '3c2e3309046'
down_revision = '3a3f6f8e6c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
