"""empty message

Revision ID: 495abccb4a6
Revises: 113472c3507
Create Date: 2015-09-11 18:01:13.382075

"""

# revision identifiers, used by Alembic.
revision = '495abccb4a6'
down_revision = '113472c3507'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
