"""empty message

Revision ID: 56cb9000f7e
Revises: None
Create Date: 2015-08-15 22:51:24.662706

"""

# revision identifiers, used by Alembic.
revision = '56cb9000f7e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('test', sa.VARCHAR(length=22), autoincrement=False, nullable=True))
    ### end Alembic commands ###
