"""empty message

Revision ID: 58de734bd40
Revises: 56cb9000f7e
Create Date: 2015-08-15 22:53:10.032405

"""

# revision identifiers, used by Alembic.
revision = '58de734bd40'
down_revision = '56cb9000f7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    ### end Alembic commands ###
