"""empty message

Revision ID: 8fe8a5f5de
Revises: 1c8e438ef34
Create Date: 2015-08-27 14:27:40.009437

"""

# revision identifiers, used by Alembic.
revision = '8fe8a5f5de'
down_revision = '1c8e438ef34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
